/*
 * main.c — STM32F401RE Edge-ML Motor Fault Classifier
 *
 * Placeholder. Not yet generated by STM32CubeMX / STM32CubeIDE.
 *
 * Intended structure once real:
 *   - HAL/LL init (clocks, GPIO, SPI for ADXL345, ADC for ACS712, TIM for encoder, USART for telemetry)
 *   - Existing PID motor control loop (ported from project 1)
 *   - Fixed-size sample buffer fill (vibration + current), windowed
 *   - TODO(step 3): CMSIS-DSP FFT / band-energy feature extraction on each window
 *   - TODO(step 8): CMSIS-NN / generated model inference call on extracted features
 *   - TODO(step 8): UART streaming of classification label + telemetry
 *   - TODO(step 9): cycle counting around the inference call for latency profiling
 *
 * Do not fill this in until training/export/ has produced a final model
 * (pipeline steps 1-7 come first).
 */

int main(void)
{
    /* TODO(step 1): peripheral init — SPI (ADXL345), ADC (ACS712), TIM (encoder), USART */
    /* TODO: port PID control loop from project 1 firmware */

    while (1)
    {
        /* TODO(step 1): sample vibration + current into window buffer */
        /* TODO(step 8): FFT -> feature vector -> CMSIS-NN inference -> class label */
        /* TODO(step 8): UART: stream label + telemetry */
    }
}
