/*
 * main.c — STM32F401RE Edge-ML Motor Fault Classifier
 *
 * Firmware pipeline step 1: sensor wiring alongside existing PID motor
 * control. This file assumes CubeMX has generated the peripheral handles
 * referenced below (hspi1, hadc1, htim2, htim3, huart2) — it has NOT been
 * generated yet. Generate the .ioc first (see main.h for the required
 * peripheral config), then regenerate this file; CubeMX preserves anything
 * inside "USER CODE" markers, which is where the driver/sampling logic
 * below belongs once real init code exists above it.
 */

#include "main.h"
#include "adxl345.h"
#include "acs712.h"
#include "encoder.h"
#include "uart_stream.h"

/* TODO(CubeMX): these become extern declarations generated by CubeMX once
 * the .ioc exists — remove these manual externs at that point. */
extern SPI_HandleTypeDef  hspi1;
extern ADC_HandleTypeDef  hadc1;
extern TIM_HandleTypeDef  htim2; /* encoder */
extern UART_HandleTypeDef huart2;

static ADXL345_Handle_t accel;
static ACS712_Handle_t  current_sensor;
static Encoder_Handle_t encoder;

/* Rolling window buffers, filled at SAMPLE_RATE_HZ, consumed once full.
 * TODO(step 3): hand a full window off to CMSIS-DSP FFT feature extraction
 * instead of just resetting the index. */
static int16_t vib_window[WINDOW_SIZE_SAMPLES];
static float   cur_window[WINDOW_SIZE_SAMPLES];
static uint16_t window_idx = 0;

/* TODO(CubeMX): call this from a TIM3 interrupt at SAMPLE_RATE_HZ, not by
 * polling in the main loop. Polling won't hold a stable sample rate once
 * the PID control loop is also running in the same loop — jitter here
 * directly corrupts the FFT features downstream. */
static void SampleTick(void)
{
    ADXL345_Raw_t sample;

    if (ADXL345_ReadRaw(&accel, &sample) == HAL_OK) {
        /* TODO: decide X, Y, Z, or magnitude as the model input — storing
         * X only for now, revisit once sensor mounting orientation on the
         * rig is finalized. Imbalance/looseness vibration direction
         * matters for which axis actually carries the signal. */
        vib_window[window_idx] = sample.x;
    }

    cur_window[window_idx] = ACS712_ReadCurrent_mA(&current_sensor);

#if STREAM_RAW_SAMPLES
    /* Data-collection mode: stream every raw sample so collect_data.py can
     * log it. See training/data_prep/collect_data.py for the receiver and
     * uart_stream.h for the wire format. */
    UART_SendSample(&huart2, vib_window[window_idx], cur_window[window_idx]);
#endif

    window_idx++;
    if (window_idx >= WINDOW_SIZE_SAMPLES) {
        window_idx = 0;
        /* TODO(step 3): once STREAM_RAW_SAMPLES is turned off, FFT + band-
         * energy extraction on vib_window/cur_window belongs here — see
         * firmware/Drivers/BSP/fft_features.h for the extraction call.
         * TODO(step 8): once a model exists, run inference on the extracted
         * features and call UART_SendLabel() with the result instead of
         * UART_SendSample() above. */
    }
}

int main(void)
{
    /* TODO(CubeMX): HAL_Init(), SystemClock_Config(), MX_GPIO_Init(),
     * MX_SPI1_Init(), MX_ADC1_Init(), MX_TIM2_Init(), MX_TIM3_Init(),
     * MX_USART2_UART_Init() — none of this exists until the .ioc is
     * generated. */

    /* TODO: port PID control loop init from the project 1 firmware here */

    if (ADXL345_Init(&accel, &hspi1, GPIOA, GPIO_PIN_4 /* TODO: confirm actual CS pin/port */,
                      ADXL345_RATE_800HZ) != HAL_OK) {
        /* DEVID mismatch or SPI failure — wrong mode, wrong CS pin, or a
         * wiring fault. Do not silently continue past this in the real
         * build; you'll spend hours debugging garbage vibration data that
         * traces back to this. */
        Error_Handler();
    }

    ACS712_Init(&current_sensor, &hadc1, ADC_CHANNEL_0, 3300.0f);
    /* Motor must be fully stopped here — see acs712.h HARDWARE WARNING
     * about output voltage range before this line runs on real hardware. */
    ACS712_Calibrate(&current_sensor, 100);

    Encoder_Init(&encoder, &htim2, 0 /* TODO: counts_per_rev from motor + gearbox datasheet */);

    while (1)
    {
        /* TODO(CubeMX): SampleTick() belongs in a TIM3 ISR at
         * SAMPLE_RATE_HZ — see note above the function. Placeholder call
         * removed here on purpose; wiring it as a bare while-loop call
         * would produce a sample rate that drifts with whatever else runs
         * in this loop, which defeats the point of a fixed-rate window. */

        /* TODO: port PID control loop update from the project 1 firmware here */
    }
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) { }
}
